# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/36fcdadd-1a60-495f-bcf8-7d15a15ef678";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CF52-0D50";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # 128GB SD card in the external slot - holds /home so the small eMMC only
  # needs to fit /nix/store. nofail + automount so a missing/removed card
  # doesn't block boot, it just mounts on first access to /home.
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/02bfcad5-927d-42cf-a963-55272982adba";
      fsType = "ext4";
      options = [ "nofail" "x-systemd.automount" "x-systemd.device-timeout=5s" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
