# PLACEHOLDER - this was NOT generated by nixos-generate-config on the real
# machine (no access to roma from here). Boot the NixOS installer on roma,
# run `nixos-generate-config --root /mnt`, and replace this whole file with
# its output before trying to switch/build.
#
# Left here as a plausible starting point for a Lenovo 500e Gen2
# (Celeron N4100, eMMC storage, no NVMe/SATA) assuming MrChromebox full UEFI
# ROM firmware is flashed - adjust availableKernelModules/fileSystems to
# match whatever the installer actually reports.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "mmc_block" "sdhci_pci" "sdhci_acpi" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # TODO: replace with the real UUIDs from nixos-generate-config
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0000-0000";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
