# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/36fcdadd-1a60-495f-bcf8-7d15a15ef678";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CF52-0D50";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # 128GB SD card in the external slot - holds /home so the small eMMC only
  # needs to fit /nix/store. This card is slow/flaky to enumerate - observed
  # anywhere from a few seconds to several minutes after boot, sometimes with
  # a failed init attempt first. nofail so local-fs.target/multi-user.target
  # (ssh, networking, etc.) never wait on it. But note: nofail does NOT save
  # the graphical login session - systemd-logind adds its own hard
  # RequiresMountsFor=/home to every session scope, so greetd will keep
  # failing to log in (crash-looping Hyprland) until /home is actually
  # mounted, no matter what options are set here. See greetd's
  # after/wants=home.mount in configuration.nix, which gives the mount a
  # single, generous, ordered attempt before greetd's first try instead of
  # many short racing ones. The udev rule in configuration.nix mounts it for
  # real whenever the card actually shows up, as a fallback for whenever this
  # timeout isn't enough - greetd will keep retrying and self-heal once that
  # lands, just noisily.
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/02bfcad5-927d-42cf-a963-55272982adba";
      fsType = "ext4";
      options = [ "nofail" "x-systemd.device-timeout=45s" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
