[general]
font-sans = "Monaspace Neon"
font-mono = "Monaspace Neon"

[bar]
bg = "transparent"
button-variant = "icon-square"
button-bg-opacity = 65
button-rounding = "full"
button-gap = 1.0499999523162842
button-group-opacity = 65
button-group-rounding = "full"
dropdown-shadow = false

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
]
right = [
    "systray",
    { name = "left", modules = [
    "bluetooth",
    "network",
    "battery",
    "clock",
] },
    "notifications",
]

[[bar.layout.center]]
name = "media_group"
modules = [
    "media",
    "cava",
    "volume",
]

[styling]
rounding = "md"
theme-provider = "matugen"
matugen-scheme = "content"
matugen-contrast = 0.19727891156462585
pywal-saturation = 0.0

[styling.palette]
bg = "#11111b"
surface = "#181825"
elevated = "#1e1e2e"
fg = "#cdd6f4"
fg-muted = "#bac2de"
primary = "#b4befe"
red = "#f38ba8"
yellow = "#f9e2af"
green = "#a6e3a1"
blue = "#74c7ec"

[modules.battery]
button-bg-color = "transparent"

[modules.bluetooth]
border-color = "yellow"
icon-bg-color = "yellow"
label-color = "yellow"
button-bg-color = "transparent"

[modules.cava]
noise-reduction = 0.7006802721088435
style = "wave"
direction = "mirror"
button-bg-color = "transparent"
bar-gap = 3
left-click = "dropdown:audio"
scroll-up = "volume-step.sh up"
scroll-down = "volume-step.sh down"

[modules.clock]
format = "%a, %d %b %H:%M"
border-color = "yellow"
icon-show = false
icon-bg-color = "yellow"
label-color = "yellow"
button-bg-color = "transparent"
dropdown-show-seconds = true

[modules.hyprland-workspaces]
min-workspace-count = 3
app-icons-show = true
icon-gap = 0.20000000298023224
label-size = 0.800000011920929

[modules.hyprland-workspaces.app-icon-map]
"title:*YouTube*" = "si-youtube"
"*kitty*" = "tb-terminal-2-symbolic"
"title:*Unity*" = "si-unity-symbolic"
"*firefox*" = "si-firefoxbrowser"
"title:*Jenkins*" = "si-jenkins"

[modules.media]
icon-type = "spinning-disc"
label-max-length = 30
button-bg-color = "transparent"

[modules.network]
border-color = "yellow"
icon-bg-color = "yellow"
label-color = "yellow"
button-bg-color = "transparent"

[modules.notifications]
icon-bg-color = "blue"
label-show = false

[modules.volume]
icon-show = false
icon-bg-color = "accent"
label-color = "accent"
button-bg-color = "transparent"
scroll-up = "volume-step.sh up"
scroll-down = "volume-step.sh down"

[wallpaper]
transition-type = "random"
transition-duration = 0.800000011920929
cycling-directory = "/home/mightypancake/nixos/wallpapers/adventure.jpeg"
cycling-mode = "shuffle"
cycling-interval-mins = 1
cycling-same-image = true
